import { createEvidenceCompatibilityReviewer, runSequentialReview } from "../.kiro/kiro-repo-guidance-setup/reviewers.ts";
import { COMPLETE_REVIEW_STATEMENT, OWNER_DECISIONS, OWNER_DECISION_IDS, REQUIRED_SURFACE_VERSIONS } from "../.kiro/kiro-repo-guidance-setup/contracts.ts";
const ROOT = "D:\\23082026";

function passingRun(surface) { const sv = REQUIRED_SURFACE_VERSIONS.find(s => s.surface === surface); return { validationId: `v-${surface}-${sv.version}`, action: "surface", repositoryRootOrActiveSurface: surface, surface, version: sv.version, scope: "x", executionLayer: "surface_validation", startedAtUtc: "2026-08-25T00:00:00.000Z", result: "pass", commandOrInteraction: "x", exitCodeOrOutcome: "exit 0", evidenceRefs: [`evidence-${surface}`], unverifiedItems: [], blocker: "none" }; }
const allRuns = REQUIRED_SURFACE_VERSIONS.map(sv => passingRun(sv.surface));
const allRecords = REQUIRED_SURFACE_VERSIONS.map(sv => { const run = passingRun(sv.surface); return { ...sv, status: "applicable", documentedBehavior: [], observedBehavior: [], evidenceFreshness: "fresh", versionSensitiveClaim: false, validationAction: "x", validationRunRefs: [run.validationId], enablementStatus: "enabled-valid", unsupportedClaims: [], migrationConstraints: [], rollbackPathRef: `rb-${sv.surface}` }; });

function sourceInventory() { return { reviewDateUtc: "2026-08-25", activeSurfaces: ["Local_Repository_Surface"], discoveryMethod: "file_read", records: [{ sourceId: "src-1", kind: "repository_file", locator: "AGENTS.md", reviewDateUtc: "2026-08-25", retrievalMethod: "file_read", surfaceApplicability: ["Local_Repository_Surface"], versionSensitiveClaim: false, availability: "available", evidenceState: "Documented", provenance: { observer: "x", cwdOrSurface: ROOT, commandOrPath: "AGENTS.md", result: "read" }, trustDecision: "trusted", claims: [], validationRunRefs: [], disposition: "retain" }], unavailableFindings: [] }; }

const decisions = OWNER_DECISIONS.map(d => ({ ...d, approvalStatus: "owner-approved", unresolvedStatus: "resolved" }));
const evReq = { inputStageRef: "integration-gate-1", sourceInventory: sourceInventory(), coverageMatrix: { entries: [{ coverageId: "cov-1", sourceId: "src-1", url: "https://kiro.dev/docs", family: "docs", discoveryMethod: "sitemap", reviewDateUtc: "2026-08-25", surface: "Local_Repository_Surface", applicability: "applicable", keyConvention: "guidance", versionSensitiveClaim: false, evidenceProvenanceRef: "prov-1", availability: "available", disposition: "retain", validationAction: "none", status: "reviewed" }], completeReviewStatement: COMPLETE_REVIEW_STATEMENT, complete: true, unavailableCandidateRefs: [], blockers: [] }, exclusions: { entries: [] }, artifactInventory: [{ artifactId: "artifact:reviewer-fixture", kind: "Kiro_Skill", path: ".kiro/skills/repo-map/SKILL.md", inventoryStatus: "present and readable", owner: "repository owner", configurationScope: "project", activationCondition: "x", canonicalSource: "AGENTS.md", evidenceState: "Observed", disposition: "retain", maintenanceRisk: "low", evidenceRefs: ["src-1"], validationRunRefs: [], rollbackPath: "no rollback applies" }], compatibilityRecords: allRecords, ownerDecisions: decisions, validationRuns: allRuns };
const ev = createEvidenceCompatibilityReviewer().review(evReq);
console.log("ev:", ev.status, ev.blockers);

const handover = { generatedAtUtc: "2026-08-25T00:00:00.000Z", reviewDateUtc: "2026-08-25", completeReviewStatement: COMPLETE_REVIEW_STATEMENT, firstReadPath: ["AGENTS.md"], coverageMatrixRef: "cov-1", exclusionRegisterRef: "excl-1", officialFamilyStatuses: [], surfaceCompatibilityStatement: "x", configurationPrecedenceMapRef: "prec-1", capabilityDispositionTableRef: "disp-1", reviewerStageRefs: [ev.output?.handoff.handoffId ?? "handoff-EvidenceCompatibilityReviewer", "handoff-SafetyRollbackReviewer"], ownerDecisionRefs: [...OWNER_DECISION_IDS], evidenceStateLegend: [], artifactDispositions: [{ artifactId: "artifact:reviewer-fixture", canonicalPath: ".kiro/skills/repo-map/SKILL.md", disposition: "retain", evidenceRefs: ["src-1"], reason: "x", activationCondition: "y", owner: "repository owner", rollbackPath: "no rollback applies" }], validationRuns: allRuns, knownGaps: [], rollbackRecords: [{ rollbackId: "rb-1", targetArtifactOrScope: "x", preChangeStateRef: "snapshot-1", rollbackAction: "y", expectedSuccessSignal: "z", observedEvidence: "z", result: "pass", verificationRunRef: "v1", owner: "x" }], maintenanceTriggers: [], limitations: [] };
const seq = runSequentialReview({ evidence: evReq, safety: { approvalBoundaries: [{ boundaryId: "ab-1", scope: "project", requestedChange: "x", targetSurface: "Local_Repository_Surface", owner: "repository owner", approvalStatus: "approved", approvalDate: "2026-08-25", preChangeStateRef: "snapshot-1", securityBoundary: "x", expectedSideEffects: ["x"], rollbackPathRef: "rollback-1" }], policyFindings: [], snapshots: ["snapshot-1"], knownGaps: { entries: [] }, rollbackRecords: [{ rollbackId: "rb-1", targetArtifactOrScope: "x", preChangeStateRef: "snapshot-1", rollbackAction: "y", expectedSuccessSignal: "z", observedEvidence: "z", result: "pass", verificationRunRef: "v1", owner: "x" }], proposedHandover: handover } });
console.log("bothReviewerStagesPass:", seq.bothReviewerStagesPass);
if (!seq.bothReviewerStagesPass) { console.log("ev2:", seq.evidenceReview.status, seq.evidenceReview.blockers); console.log("saf:", seq.safetyReview?.status, seq.safetyReview?.blockers); }
